# Generated by Django 5.2.7 on 2025-10-31 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
